### ISSUE TITLE
 Data Collection

### ISSUE THREAD

**Issue by divyamraj18** [animysore/LSTM-rap-generation#1]
for song in album.find_next('ol').children:
    ------>    a = re.search('\:(.*)', song.b.find('a').get('href',''))
        #song.b.a['href']
        data.append({
          ------->  'url': song.b.find('a').get('href',''),
            'name': a.group(1)
actually there is some problems in these lines
i tried to run this bt it gives some error stating that a has no attribute group
actually there was some problem with the lines starting with------> bt i changed them and now they are working please update

**Comment by animysore** [comment]
Fixed this. 
Thank you @divyamraj18 :smile:
